name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Generate Secrets.swift
      run: ./SecretsManager/Scripts/generate_secrets_swift.sh

    - name: Install dependencies
      run: |
        bundle install # Si usas Bundler
        pod install || true # Si usas CocoaPods, opcional

    - name: Build app
      run: xcodebuild -workspace SecretsManager.xcworkspace -scheme SecretsManager -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' build
